package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

var updateNotices = flag.Bool("update", false, "rewrite THIRD_PARTY_NOTICES_BINARY (go test ./cmd/oge -run TestBinaryNotices -update)")

const noticesFile = "../../THIRD_PARTY_NOTICES_BINARY"

// The release archive ships THIRD_PARTY_NOTICES_BINARY: the licence and
// notice files of every module compiled into the release binary, on every
// platform it is built for, and of the Go standard library. This test
// regenerates it and fails when the committed copy is stale, so a go.mod
// change can't ship without its notices.
func TestBinaryNotices(t *testing.T) {
	t.Parallel()
	got := binaryNotices(t)
	if *updateNotices {
		if err := os.WriteFile(noticesFile, []byte(got), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	want, err := os.ReadFile(noticesFile)
	if err != nil {
		t.Fatal(err)
	}
	if got != strings.ReplaceAll(string(want), "\r\n", "\n") {
		t.Errorf("THIRD_PARTY_NOTICES_BINARY is stale; run go test ./cmd/oge -run TestBinaryNotices -update")
	}
}

type listedModule struct {
	Path, Version, Dir string
	Main               bool
	Replace            *listedModule
}

func binaryNotices(t *testing.T) string {
	t.Helper()
	mods := map[string]listedModule{}
	for _, goos := range []string{"linux", "darwin", "windows"} {
		cmd := exec.Command("go", "list", "-deps", "-json=Module,Standard", ".")
		cmd.Env = append(os.Environ(), "GOOS="+goos, "CGO_ENABLED=0", "GOFLAGS=-mod=readonly")
		out, err := cmd.Output()
		if err != nil {
			t.Fatalf("go list for %s: %v", goos, err)
		}
		dec := json.NewDecoder(bytes.NewReader(out))
		for dec.More() {
			var p struct {
				Standard bool
				Module   *listedModule
			}
			if err := dec.Decode(&p); err != nil {
				t.Fatal(err)
			}
			if p.Standard || p.Module == nil || p.Module.Main {
				continue
			}
			m := *p.Module
			if m.Replace != nil {
				m = *m.Replace
			}
			mods[m.Path] = m
		}
	}
	paths := make([]string, 0, len(mods))
	for p := range mods {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	var b strings.Builder
	b.WriteString("Third-party notices for the oge binary\n")
	b.WriteString("======================================\n\n")
	b.WriteString("The oge binary compiles in the Go standard library and the modules below\n")
	b.WriteString("(release builds for linux, darwin and windows, CGO_ENABLED=0). Each one's\n")
	b.WriteString("licence and notice files follow. Generated by\n")
	b.WriteString("`go test ./cmd/oge -run TestBinaryNotices -update`; don't edit by hand.\n")

	goroot, err := exec.Command("go", "env", "GOROOT").Output()
	if err != nil {
		t.Fatal(err)
	}
	// Some installs (Homebrew) keep the Go LICENSE beside GOROOT.
	root := strings.TrimSpace(string(goroot))
	section(t, &b, "Go standard library (https://go.dev)", root, filepath.Dir(root))
	for _, p := range paths {
		m := mods[p]
		section(t, &b, m.Path+" "+m.Version, m.Dir)
	}
	return b.String()
}

// section appends a module's licence and notice files, from the first of
// dirs that has each name.
func section(t *testing.T, b *strings.Builder, title string, dirs ...string) {
	t.Helper()
	found := map[string]string{} // upper-case name: path
	for _, dir := range dirs {
		entries, err := os.ReadDir(dir)
		if err != nil {
			t.Fatalf("%s: %v", title, err)
		}
		for _, e := range entries {
			name := strings.ToUpper(e.Name())
			base := strings.TrimSuffix(strings.TrimSuffix(strings.TrimSuffix(name, ".MD"), ".TXT"), ".RST")
			notice := base == "LICENSE" || base == "LICENCE" || base == "COPYING" || strings.HasPrefix(base, "LICENSE-") ||
				base == "NOTICE" || base == "PATENTS"
			if notice && !e.IsDir() && found[name] == "" {
				found[name] = filepath.Join(dir, e.Name())
			}
		}
	}
	var names []string
	licensed := false
	for name := range found {
		names = append(names, name)
		licensed = licensed || !strings.HasPrefix(name, "NOTICE") && !strings.HasPrefix(name, "PATENTS")
	}
	if !licensed {
		t.Fatalf("%s: no licence file in %v", title, dirs)
	}
	sort.Strings(names)
	fmt.Fprintf(b, "\n%s\n%s\n%s\n", strings.Repeat("-", 79), title, strings.Repeat("-", 79))
	for _, name := range names {
		text, err := os.ReadFile(found[name])
		if err != nil {
			t.Fatal(err)
		}
		fmt.Fprintf(b, "\n[%s]\n\n%s\n", filepath.Base(found[name]), strings.TrimRight(strings.ReplaceAll(string(text), "\r\n", "\n"), "\n"))
	}
}
